package enum

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}

func TestGenerate_StringEnum(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "color.go", `package mypkg

type Color string

const (
	Red   Color = "red"
	Green Color = "green"
	Blue  Color = "blue"
)
`)

	if err := Generate(dir, "Color"); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	out, err := os.ReadFile(filepath.Join(dir, "color_enum.gen.go"))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	src := string(out)

	checks := []string{
		"package mypkg",
		"func (t Color) IsValid() bool",
		"func (Color) Values() []Color",
		"func (t Color) String() string",
		"func ParseColor(s string)",
		"case \"red\":",
		"case \"green\":",
		"case \"blue\":",
		"func (t Color) MarshalJSON()",
		"func (t *Color) UnmarshalJSON(",
		"func (t Color) Value() (driver.Value, error)",
		"func (t *Color) Scan(",
		"func ColorFromIndex(idx int) Color",
		"func (t Color) Exhaustive() string",
		"func (t Color) Index() int",
	}
	for _, c := range checks {
		if !strings.Contains(src, c) {
			t.Errorf("generated code missing %q", c)
		}
	}
}

func TestGenerate_NoConstants(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "empty.go", `package mypkg

type Color string
`)

	err := Generate(dir, "Color")
	if err == nil || !strings.Contains(err.Error(), "no constants") {
		t.Fatalf("expected 'no constants' error, got %v", err)
	}
}

func TestGenerate_NoGoFiles(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	err := Generate(dir, "Color")
	if err == nil {
		t.Fatalf("expected error for empty dir")
	}
}

func TestGenerate_SkipsPreviouslyGenerated(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "status.go", `package mypkg

type Status string

const (
	Active   Status = "active"
	Inactive Status = "inactive"
)
`)
	// A previously-generated file should be ignored on subsequent runs to avoid
	// the parser tripping on duplicate methods.
	writeFile(t, dir, "status_enum.gen.go", `// Code generated by Typed Enum Generator; DO NOT EDIT.
package mypkg
`)

	if err := Generate(dir, "Status"); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "status_enum.gen.go")); err != nil {
		t.Fatalf("generated file missing: %v", err)
	}
}
