package enum

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// EnumInfo holds the data extracted from the source files used to generate code.
type EnumInfo struct {
	PkgName   string
	TypeName  string
	Kind      string // "string" or "int"
	Constants []string
	Values    []string // raw constant value
	HasString bool
	HasInt    bool
}

// Generate is the main entry point invoked by the command.
func Generate(dir string, typeName string) error {
	fset := token.NewFileSet()
	// Parse every .go file in the directory, excluding previously generated output.
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_enum.gen.go")
	}, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parser error: %w", err)
	}

	var info EnumInfo
	var pkgName string
	var allDecls []ast.Decl

	// Walk every package (typically only one) and collect all declarations.
	for _, pkg := range pkgs {
		if pkgName == "" {
			pkgName = pkg.Name
		}
		for _, f := range pkg.Files {
			allDecls = append(allDecls, f.Decls...)
		}
	}

	if pkgName == "" {
		return fmt.Errorf("no Go files found in %s", dir)
	}

	info.PkgName = pkgName
	info.TypeName = typeName

	// Find constants of the requested type across every declaration.
	for _, decl := range allDecls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}

		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok || len(valueSpec.Names) == 0 {
				continue
			}

			// Skip constants that do not belong to the target type.
			if valueSpec.Type != nil {
				ident, ok := valueSpec.Type.(*ast.Ident)
				if !ok || ident.Name != typeName {
					continue
				}
			} else {
				// Constant without an explicit type: skip.
				continue
			}

			// Collect the value for each constant name.
			for i, name := range valueSpec.Names {
				info.Constants = append(info.Constants, name.Name)
				if len(valueSpec.Values) > i {
					if lit, ok := valueSpec.Values[i].(*ast.BasicLit); ok {
						info.Values = append(info.Values, strings.Trim(lit.Value, `"`))
					} else {
						info.Values = append(info.Values, "")
					}
				} else {
					info.Values = append(info.Values, "")
				}
			}
		}
	}

	if len(info.Constants) == 0 {
		return fmt.Errorf("no constants of type %s found", typeName)
	}

	// Decide the underlying kind from the observed values.
	if len(info.Values) > 0 && info.Values[0] != "" {
		if _, err := fmt.Sscanf(info.Values[0], "%d", new(int)); err == nil {
			info.Kind = "int"
			info.HasInt = true
		} else {
			info.Kind = "string"
			info.HasString = true
		}
	} else {
		info.Kind = "string"
		info.HasString = true
	}

	if info.Kind == "int" {
		for _, v := range info.Values {
			if _, err := fmt.Sscanf(v, "%d", new(int)); err == nil {
				info.HasInt = true
			} else {
				info.HasString = true
			}
		}
	}

	// Render the generated code.
	return generateCode(dir, info)
}

// Template for the generated code.
const enumTemplate = `// Code generated by Typed Enum Generator; DO NOT EDIT.

package {{.PkgName}}

{{if .HasString}}
import "fmt"
import "encoding/json"
import "database/sql/driver"
{{end}}


// ===== Generated methods for enum {{.TypeName}} =====

// IsValid reports whether the value is one of the declared constants.
func (t {{.TypeName}}) IsValid() bool {
	switch t {
{{- $constants := .Constants}}
	case {{range $i, $c := $constants}}{{if $i}}, {{end}}{{$c}}{{end}}:
		return true
	default:
		return false
	}
}

// Values returns every constant of the enum.
func ({{.TypeName}}) Values() []{{.TypeName}} {
	return []{{.TypeName}}{
{{- range .Constants}}
		{{.}},
{{- end}}
	}
}

{{if .HasString}}
// String returns the underlying string value.
func (t {{.TypeName}}) String() string {
	return string(t)
}

// Parse{{.TypeName}} converts a string into the enum value.
func Parse{{.TypeName}}(s string) ({{.TypeName}}, error) {
	switch s {
{{- range $i, $c := .Constants}}
	case "{{index $.Values $i}}":
		return {{$c}}, nil
{{- end}}
	default:
		return {{(index .Constants 0)}}, fmt.Errorf("invalid {{.TypeName}}: %s", s)
	}
}
{{end}}

// MarshalJSON implements the json.Marshaler interface.
func (t {{.TypeName}}) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (t *{{.TypeName}}) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	val, err := Parse{{.TypeName}}(s)
	if err != nil {
		return err
	}
	*t = val
	return nil
}

// Value implements the driver.Valuer interface for database/sql.
func (t {{.TypeName}}) Value() (driver.Value, error) {
	return string(t), nil
}

// Scan implements the sql.Scanner interface.
func (t *{{.TypeName}}) Scan(value interface{}) error {
	if value == nil {
		*t = {{index .Constants 0}}
		return nil
	}
	s, ok := value.(string)
	if !ok {
		return fmt.Errorf("expected string, got %T", value)
	}
	val, err := Parse{{.TypeName}}(s)
	if err != nil {
		return err
	}
	*t = val
	return nil
}

// {{.TypeName}}FromIndex returns the enum value at the given index.
func {{.TypeName}}FromIndex(idx int) {{.TypeName}} {
	switch idx {
{{- range $i, $c := .Constants}}
	case {{$i}}:
		return {{$c}}
{{- end}}
	default:
		return {{(index .Constants 0)}} // default value
	}
}


// ===== Exhaustive switch =====
// Exhaustive forces every constant to be handled at the call site.
// If a new constant is added without updating this method, the call panics
// at runtime instead of silently returning an empty value.
func (t {{.TypeName}}) Exhaustive() string {
	switch t {
{{- range $i, $c := .Constants}}
	case {{$c}}:
		return "{{index $.Values $i}}"
{{- end}}
	default:
		panic("unreachable: enum {{.TypeName}} has unhandled constant")
	}
}

// Index returns the 0-based position of the constant.
// Useful with EnumSet or any structure that depends on a fixed ordering.
func (t {{.TypeName}}) Index() int {
	switch t {
{{- range $i, $c := .Constants}}
	case {{$c}}:
		return {{$i}}
{{- end}}
	default:
		return -1 // invalid value, should never happen
	}
}
`

func generateCode(dir string, info EnumInfo) error {
	outputName := strings.ToLower(info.TypeName) + "_enum.gen.go"
	outputPath := filepath.Join(dir, outputName)

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("cannot create output file: %w", err)
	}
	defer f.Close()

	tmpl, err := template.New("enum").Parse(enumTemplate)
	if err != nil {
		return fmt.Errorf("template error: %w", err)
	}

	return tmpl.Execute(f, info)
}
