package enum

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}

func TestGenerate_StringEnum(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "color.go", `package mypkg

type Color string

const (
	Red   Color = "red"
	Green Color = "green"
	Blue  Color = "blue"
)
`)

	if err := Generate(dir, "Color"); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	out, err := os.ReadFile(filepath.Join(dir, "color_enum.gen.go"))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	src := string(out)

	checks := []string{
		"package mypkg",
		"func (t Color) IsValid() bool",
		"func (Color) Values() []Color",
		"func (t Color) String() string",
		"func ParseColor(s string)",
		"case \"red\":",
		"case \"green\":",
		"case \"blue\":",
		"func (t Color) MarshalJSON()",
		"func (t *Color) UnmarshalJSON(",
		"func (t Color) Value() (driver.Value, error)",
		"func (t *Color) Scan(",
		"func ColorFromIndex(idx int) Color",
		"func (t Color) Exhaustive() string",
		"func (t Color) Index() int",
	}
	for _, c := range checks {
		if !strings.Contains(src, c) {
			t.Errorf("generated code missing %q", c)
		}
	}
}

func TestGenerate_NoConstants(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "empty.go", `package mypkg

type Color string
`)

	err := Generate(dir, "Color")
	if err == nil || !strings.Contains(err.Error(), "no constants") {
		t.Fatalf("expected 'no constants' error, got %v", err)
	}
}

func TestGenerate_NoGoFiles(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	err := Generate(dir, "Color")
	if err == nil {
		t.Fatalf("expected error for empty dir")
	}
}

func TestGenerate_SkipsPreviouslyGenerated(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "status.go", `package mypkg

type Status string

const (
	Active   Status = "active"
	Inactive Status = "inactive"
)
`)
	// A previously-generated file should be ignored on subsequent runs to avoid
	// the parser tripping on duplicate methods.
	writeFile(t, dir, "status_enum.gen.go", `// Code generated by Typed Enum Generator; DO NOT EDIT.
package mypkg
`)

	if err := Generate(dir, "Status"); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "status_enum.gen.go")); err != nil {
		t.Fatalf("generated file missing: %v", err)
	}
}

const colorSrc = `package mypkg
type Color string
const (
	Red   Color = "red"
	Green Color = "green"
	Blue  Color = "blue"
)
`

func TestGenerate_WithJSON_False(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	writeFile(t, dir, "color.go", colorSrc)

	if err := Generate(dir, "Color", WithJSON(false)); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	src := readGenerated(t, dir, "color_enum.gen.go")

	// JSON methods must be absent.
	for _, absent := range []string{
		"encoding/json",
		"func (t Color) MarshalJSON()",
		"func (t *Color) UnmarshalJSON(",
	} {
		if strings.Contains(src, absent) {
			t.Errorf("generated code should not contain %q", absent)
		}
	}

	// Core methods must still be present.
	for _, want := range []string{
		"func (t Color) IsValid() bool",
		"func ParseColor(s string)",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated code missing %q", want)
		}
	}
}

func TestGenerate_WithSQL_False(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	writeFile(t, dir, "color.go", colorSrc)

	if err := Generate(dir, "Color", WithSQL(false)); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	src := readGenerated(t, dir, "color_enum.gen.go")

	for _, absent := range []string{
		"database/sql/driver",
		"func (t Color) Value()",
		"func (t *Color) Scan(",
	} {
		if strings.Contains(src, absent) {
			t.Errorf("generated code should not contain %q", absent)
		}
	}
}

func TestGenerate_WithExhaustive_False(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	writeFile(t, dir, "color.go", colorSrc)

	if err := Generate(dir, "Color", WithExhaustive(false)); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	src := readGenerated(t, dir, "color_enum.gen.go")

	if strings.Contains(src, "func (t Color) Exhaustive()") {
		t.Error("generated code should not contain Exhaustive() when disabled")
	}
}

func TestGenerate_NoJSONNoSQL_NoSuperfluousImports(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	writeFile(t, dir, "color.go", colorSrc)

	if err := Generate(dir, "Color", WithJSON(false), WithSQL(false)); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	src := readGenerated(t, dir, "color_enum.gen.go")

	for _, absent := range []string{
		"encoding/json",
		"database/sql/driver",
	} {
		if strings.Contains(src, absent) {
			t.Errorf("generated code should not contain import %q", absent)
		}
	}

	// fmt ainda deve estar presente por causa de ParseColor.
	if !strings.Contains(src, `"fmt"`) {
		t.Error("generated code should still import fmt (needed by ParseColor)")
	}
}

func TestGenerate_AllDisabled_NoFmt(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	// Tipo int não gera ParseColor, logo fmt só seria necessário para SQL.
	// Com JSON=false, SQL=false e tipo int: nenhum import deve aparecer.
	writeFile(t, dir, "direction.go", `package mypkg
type Direction int
const (
	North Direction = 0
	South Direction = 1
	East  Direction = 2
	West  Direction = 3
)
`)
	if err := Generate(dir, "Direction", WithJSON(false), WithSQL(false)); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	src := readGenerated(t, dir, "direction_enum.gen.go")

	for _, absent := range []string{`"fmt"`, `"encoding/json"`, `"database/sql/driver"`} {
		if strings.Contains(src, absent) {
			t.Errorf("generated code should not contain import %q", absent)
		}
	}
}

func TestGenerate_WithOutputSuffix(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	writeFile(t, dir, "color.go", colorSrc)

	if err := Generate(dir, "Color", WithOutputSuffix("_gen.go")); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	// Arquivo com sufixo customizado deve existir.
	if _, err := os.Stat(filepath.Join(dir, "color_gen.go")); err != nil {
		t.Fatalf("expected color_gen.go, got: %v", err)
	}

	// Arquivo com sufixo padrão não deve existir.
	if _, err := os.Stat(filepath.Join(dir, "color_enum.gen.go")); err == nil {
		t.Fatal("color_enum.gen.go should not exist when suffix is overridden")
	}
}

func TestGenerate_WithOutputSuffix_SkipsOwnOutput(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	writeFile(t, dir, "color.go", colorSrc)

	// Arquivo gerado anteriormente com sufixo customizado deve ser ignorado no re-parse.
	writeFile(t, dir, "color_gen.go", `// Code generated by Typed Enum Generator; DO NOT EDIT.
package mypkg
`)
	if err := Generate(dir, "Color", WithOutputSuffix("_gen.go")); err != nil {
		t.Fatalf("Generate on re-run: %v", err)
	}
}

// ---- helpers ----

func readGenerated(t *testing.T, dir, name string) string {
	t.Helper()
	out, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		t.Fatalf("read generated file %s: %v", name, err)
	}
	return string(out)
}
